[package]
name = "op-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.0"
env_logger = "0"
serde = { version = "1.0", features = ["derive"] }
clap = {version = "4.5", features = ["derive", "string"]}
serde_json = "1.0.140"
skim = "0.16.1"
arboard = "3.5.0"
